apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbs-code-generator
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cbs-code-generator
  template:
    metadata:
      labels:
        app: cbs-code-generator
    spec:
      containers:
      - name: cbs-code-generator
        image: registry.cn-hangzhou.aliyuncs.com/peterzgy/cbs-code-generator:1.0.9
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Never
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: zgyali
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-code-generator-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: cbs-code-generator
  ports:
  - name: http
    port: 8082
    targetPort: 8082
---
#apiVersion: networking.k8s.io/v1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cbs-code-generator-ingress
spec:
  rules:
  - host: www.cbscodegen.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            serviceName: cbs-code-generator-service
            servicePort: 8082

